services:
 - docker
before_install:
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL4000 - < Dockerfile
install:
  - docker build -t git-hours .
  - docker run --rm -v $(pwd):/code ymajik/git-hours
    
    #script:
    #  - docker ps | grep -q apt-cacher-ng
